config/routes.rb
Nobq::Application.routes.draw do

  get "about_us/index"

  get "privacy/index"

  get "terms/index"

  root :to => 'welcome#index'
  get "welcome/index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "home/index"

  resources :pictures  do
    resources :messages
  end
  resources :authentications

  devise_for :users

  resources :profiles do
    resources :pictures do
      member { post :vote }
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :provider, :token, :token_secret, :uid, :user_id
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :picture_id, :parent_id
 has_ancestry

  belongs_to :picture
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :profile_id, :photo

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>", :mini => "50x50" }

  belongs_to :profile
  has_many :messages
  has_and_belongs_to_many :segments

  has_reputation :votes, source: :user, aggregated_by: :sum

  after_create :cast_first_vote

  private

  def cast_first_vote
    self.

    link_to "up", vote_profile_picture_path(picture, type: "up"), method: "post"
  end



end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :age, :bio, :city, :country_of_application, :first_name, :hobbies, :id_card_provider, :identification_number, :last_name, :marital_status, :middle_name, :occupation, :office_address, :phone_number, :residential_address, :state_of_origin, :user_id, :photo
  belongs_to :user
  has_many :pictures
  has_many :replies, :through => :pictures, :source => :messages

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>", :mini => "50x50#" }, :default_url => "/assets/missing.png"


  has_reputation :votes, source: {reputation: :votes, of: :pictures }, aggregated_by: :sum




end

app/models/segment.rb
class Segment < ActiveRecord::Base
  attr_accessible :about, :name

  has_and_belongs_to_many :pictures

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :contestant
  # attr_accessible :title, :body

  has_many :authentications
  has_one :profile
  has_many :images, :through => :profile, :source => :pictures



  after_create :create_profile
  scope :is_contestant, -> { where(contestant: true )}
  scope :not_contestant, -> { where(contestant: false) }


  private

  def create_profile
    self.profile = Profile.create
  end

  def contestant?
    where contestant=true
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @profile = Profile.find_with_reputation(:votes, :all, order: "votes desc")
  end
end

app/controllers/privacy_controller.rb
class PrivacyController < ApplicationController
  def index
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def nested_messages(messages)
    messages.map do |message, sub_messages|
      render(message) + content_tag(:div, nested_messages(sub_messages), :class => "nested_messages")
    end.join.html_safe
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="../../assets/ico/favicon.png">

  <title><%= content_for?(:title) ? yield(:title) : "Nobq" %></title>
  <%= csrf_meta_tags %>

  <!--  Stylesheet -->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <![endif]-->

</head>

<body style="padding-top: 60px">

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>">Naija Beauty Queeen</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<% if controller_name == "home" %>active<% end %> btn-inverse"><a href="<%= home_index_path %>"> <i class="glyphicon glyphicon-home"></i> Home</a></li>
        <li class="<% if controller_name == "about_us" %>active<% end %> btn-inverse"><a href="<%= about_us_index_path %>"> <i class="glyphicon glyphicon-user"></i> About Us</a></li>
        <li class="<% if controller_name == "pictures" %>active<% end %> btn-inverse"><a href="<%= pictures_path %>"><i class="glyphicon glyphicon-camera"></i> Pictures </a></li>
      </ul>
      <% if user_signed_in?  %>
          <ul class="nav navbar-nav navbar-right">
            <li><a><%= current_user.email %> ( <%= pluralize(current_user.profile.reputation_for(:votes).to_i, "point") if current_user.contestant %> ) </a> </li>
            <li class="dropdown">
              <span class="dropdown-toggle" data-toggle="dropdown" style="cursor: pointer;" ><img class="profile-mini-pic" src = "<%= current_user.profile.photo.url(:mini) %>"> <b class="caret"></b></span>
              <ul class="dropdown-menu">
                <li><a href="<%= edit_profile_path(current_user) %>">Update Profile</a></li>
                <li class="divider"></li>
                <li><a href="#"></a></li>
                <li><a href="#">View your Pictures</a></li>
                <li><a href="#">logout</a></li>
              </ul>
            </li>
          </ul>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
              <li>
               <%= form_for("user", :url => user_session_path, :class => "form-inline") do |f| %>
                <div class="form-group">
                    <%= f.email_field :email, :autofocus => true, :placeholder => "Email", :class => "app-login-form form-control1" %>

                    <%= f.password_field :password, :placeholder => "Password", :class => "app-login-form form-control1" %>
                  <%= f.check_box :remember_me %> <%= f.label :R_me, :class => "form-inline-pass" %>
                  <%= f.submit "login" %>
                </div>
                <% end %>
              </li>

          </ul>
      <% end %>
    </div><!--/.nav-collapse -->
  </div>
</div>
<div class="bs-sidebar hidden-print affix left-f-t" role="complementary">
  <ul class="nav bs-sidenav">
    <li>
      <a href="components#btn-groups"> <%= image_tag "fb.png", :class => "social-image" %> </a>

    </li>
    <li>
      <a href="components#btn-dropdowns"><%= image_tag "twitter.png", :class => "social-image" %></a>

    </li>
    <li>
      <a href="components#input-groups"><%= image_tag "sharethis_32.png", :class => "social-image" %></a>

    </li>


    <li>
      <a href="components#input-groups"><%= image_tag "googleplus.png", :class => "social-image" %></a>

    </li>

  </ul>
</div>

<div class="container">
  <div class="row">
    <div class="span9">

      <%= content_tag :p, notice, :class => 'notice' if notice.present? %>
      <%= content_tag :p, alert, :class => 'alert' if alert.present? %>

      <% if user_signed_in? %>
          <%= current_user.email %> (<%= current_user.profile.reputation_for(:votes).to_i %>) | <%= link_to "logout", destroy_user_session_path, :method => "delete" %>
      <% else %>
          <%= link_to "login", new_user_session_path %>
      <% end %>

      <%= yield %>

    </div>
<!--/span-->
  </div><!--/row-->

</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="../../assets/ico/favicon.png">

  <title>Nigeria Online Beauty Queen</title>

  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <![endif]-->

  <!-- Custom styles for this template -->
</head>
<!-- NAVBAR
================================================== -->
<body>
<div class="master-head">
  <h1>Nigeria Online Beauty Queen</h1>
  <p> Every Woman is a Beauty Queen </p>
</div>

<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>

<%= yield(:head_header) %>
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" style="margin-bottom: 0px; border-bottom:2px solid black; box-shadow: 0px 0px 0px 2px darkgrey">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "next.jpg" %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Its totally easy and free.</h1>
          <p>Its Simply click on the link below to register, check the contestant option to register as a contestant, and be on your way to becoming Nigeria's first online beauty queen </p>
          <p><a class="btn btn-large btn-primary" href="<%= new_user_registration_path %>" style="color: #ffffff;">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag "test.png" %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Every Woman is a beauty Queen</h1>
          <p>.</p>
          <p><a class="btn btn-large btn-primary" href="<%= about_us_index_path %>">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag "best.png" %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Unlimited Photos and Styles</h1>
          <p>Upload as many photos as possible and make your profile a home for all to visit and earn more points in-other for you to appear in our top gallery </p>
          <p><a class="btn btn-large btn-primary" href="<%= pictures_path %>">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="index.html#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="index.html#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->



<div class="container2">
  <div class="master-middle">
    <h1>Every Woman Is a Queen</h1>
    <p> Hurry and vote for you favourite woman </p>
  </div>

  <div class="row">
    <div class="col-md-4"><div class="carbonad">
      <p><span>Nigeria Online Beauty Queen</span> is Nigeria's first and biggest online facial beauty contest ever, were every
        eligible nigeria woman anywhere in the world is privileged to contest in the largest online beauty pageant and be crowned the next quarter's nigeria online beauty queen.</p>
      <table>
        <tr>
        <td>
          <div class = "image-number1">
            <div>
              <%= image_tag ("best.png"), :class => "doc" %>
            </div>
          </div>
        </td>

        <td>
          <div class = " image-number1">
            <div>
              <%= image_tag ("best.png"), :class => "doc" %>
            </div>
          </div>
        </td>

        <td>
          <div class = " image-number1">
            <%= image_tag ("best.png"), :class => "doc" %>
          </div>

      </td>
      </tr>

    </table>


    </div></div>
    <div class="col-md-8 pull-right">
      <table>
      <td>
        <div class = " image-number1">
          <div class="image">
            <%= image_tag ("best.png"), :class => "top-rated" %>
          </div>
        </div>

      </td>
      <td>
        <div class = " image-number1">
          <div>
            <%= image_tag ("best.png"), :class => "top-rated" %>
          </div>
        </div>
      </td>

      <td>
        <div class = " image-number1">
          <div>
            <%= image_tag ("best.png"), :class => "top-rated" %>
          </div>
        </div>
      </td>

      <td>
        <div class = " image-number1">
          <%= image_tag ("best.png"), :class => "top-rated" %>
        </div>

    </td>
    <tr>
      <td>
        <div class = " image-number1">
          <div class="image">
            <%= image_tag ("bg4.JPG"), :class => "top-rated" %>
          </div>
        </div>

      </td>
      <td>
        <div class = " image-number1">
          <div>

            <%= image_tag ("bg4.JPG"), :class => "top-rated" %>
          </div>
        </div>
      </td>

      <td>
        <div class = " image-number1">
          <div>
            <%= image_tag ("bg3.jpg"), :class => "top-rated" %>
          </div>
      </td>

      <td>
        <div class = " image-number1" >
          <%= image_tag ("bg2.jpg"), :class => "top-rated"  %>
        </div>
      </td>
  </tr>
  </table>
</div>
  </div>











  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="<%= home_index_path %>">Enter Main App</a></p>
    <p>&copy; Crytal Media, Inc. &middot; <a href="<%= privacy_index_path %>">Privacy</a> &middot; <a href="<%= terms_index_path %>">Terms</a></p>
  </footer>

</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>
</body>
</html>